### ISSUE TITLE
Mission "A Surprise": Recycler will be release via a seperate Dropship

### ISSUE THREAD

**Issue by BZdJunge** [BlackDragonN001/FERemastered#156]
I am not sure if it is intended, but the Recycler is usually in the same dropship like the player. 

Now, this is not the case. After the rough landing, the player have to wait until another dropship has been landed. This takes a lot of time and someone will think the mission is broken.

**Comment by GraveyBoi** [comment]
@BZdJunge I updated the mission lua due to the original being an absolute cluster in that dropship, which shouldn't have been done that way in the first place. I need to make an otf file to display to inform the player that the drop ship with the recycler is coming down shortly. Thanks for the pointer, i'll get that include so its a little more user friendly.
