### ISSUE TITLE
MERCEDF01 "Mercury Rising": Devastating Drones

### ISSUE THREAD

**Issue by BZdJunge** [BlackDragonN001/FERemastered#159]
I know this mission meant to be "hard" storywise since the EDF are unprepared against the issues with the drones and guntowers. However, since the strafe circling isn't effective anymore against any AI from 1.3+, the drones minigun is too OP.

The biggest issue is near the end when you regroup after destroying the power generators: you get attacked by multiple drones right of the bat (see the screenshot below). Playing on Hard difficulty, these drone in this quantity will destroy you in no time. Even when you fly in circles while your scouts do the rest, it requires a lot of luck. Maybe the best solution is to reduce the hitpoints by half?

![20220712194905_1](https://user-images.githubusercontent.com/107756798/179055424-24677e82-09b8-4593-b7d4-cbdc1b1b611c.jpg)

**Comment by GraveyBoi** [comment]
Ive tested this mission a number of times, proper commanding you can finish with all your scouts. although i dont disagree their minigun could use a small nerf.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: BZdJunge ***@***.***>
Sent: Thursday, July 14, 2022 2:40:12 PM
To: BlackDragonN001/FERemastered ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BlackDragonN001/FERemastered] MERCEDF01 "Mercury Rising": Devastating Drones (Issue #159)


I know this mission meant to be "hard" storywise since the EDF are unprepared against the issues with the drones and guntowers. However, since the strafe circling isn't effective anymore against any AI from 1.3+, the drones minigun is too OP.

The biggest issue is near the end when you regroup after destroying the power generators: you get attacked by multiple drones right of the bat (see the screenshot below). Playing on Hard difficulty, these drone in this quantity will destroy you in no time. Even when you fly in circles while your scouts do the rest, it requires a lot of luck. Maybe the best solution is to reduce the hitpoints by half?

[20220712194905_1]<https://user-images.githubusercontent.com/107756798/179055424-24677e82-09b8-4593-b7d4-cbdc1b1b611c.jpg>

**Comment by BZdJunge** [comment]
Usually my strategy (most of the missions with outnumbered untis) is to do the first hit against the opponents and flying circles around these while my units destroy one enemy at the time. Sure, on Hard difficulty it supposed to be challenging, but in this case is too ridiculous (or I am too nooby for Hard mode ^^)

**Comment by GraveyBoi** [comment]
ill publish a how to later :)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GraveyBoi** [comment]
https://youtu.be/8i7bndeyPnc

Uploading now. The last set of 4 you can actually leave early from and just run to safety.

**Comment by BZdJunge** [comment]
Thanks! Looks like I got unlucky in my playthough ^^
